theme: jekyll-theme-minimal
title: Madhavi Srinivasan
description: Hey there! That's me at Mt Bonnell, Austin, TX. I'm currently studying the Masters in Data Science program at the University of Washington.
logo: imgs/IMG-20160909-WA0050.jpg
